### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#100]
Our users are complaining about generally unreliable experiences using our NFSRODS deployment, so I am auditing our logs for error messages. Among them we have 171,048 instances of the error "[IRODSVirtualFileSystem] - java.net.ConnectException: Connection refused (Connection refused)".

These appear to be the most interesting relevant tracebacks; though there are other variants:

```
java.io.IOException: org.irods.jargon.core.exception.JargonException: java.net.ConnectException: Connection refused (Connection refused)
	at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.checkAcl(IRODSVirtualFileSystem.java:767) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.vfs.PseudoFs.checkAccess(PseudoFs.java:390) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.vfs.PseudoFs.checkAccess(PseudoFs.java:342) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.vfs.PseudoFs.getattr(PseudoFs.java:296) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.OperationGETATTR.getAttributes(OperationGETATTR.java:167) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.OperationGETATTR.process(OperationGETATTR.java:122) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:204) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.lambda$run$0(RpcDispatcher.java:100) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_222]
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:99) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: org.irods.jargon.core.exception.JargonException: java.net.ConnectException: Connection refused (Connection refused)
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.connect(IRODSBasicTCPConnection.java:167) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.initializeConnection(AbstractConnection.java:232) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.<init>(AbstractConnection.java:197) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.<init>(IRODSBasicTCPConnection.java:51) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl.instance(IRODSTCPConnectionFactoryImpl.java:33) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:86) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl.<init>(CollectionAndDataObjectListAndSearchAOImpl.java:69) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getCollectionAndDataObjectListAndSearchAO(IRODSAccessObjectFactoryImpl.java:464) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.getObjectType(IRODSVirtualFileSystem.java:1233) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.checkAcl(IRODSVirtualFileSystem.java:694) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_222]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_222]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.connect(IRODSBasicTCPConnection.java:142) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.initializeConnection(AbstractConnection.java:232) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.<init>(AbstractConnection.java:197) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.<init>(IRODSBasicTCPConnection.java:51) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl.instance(IRODSTCPConnectionFactoryImpl.java:33) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:86) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
```

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_222]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_222]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.connect(IRODSBasicTCPConnection.java:142) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.initializeConnection(AbstractConnection.java:232) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
```

**Comment by anderbubble** [comment]
I'll re-open with better information.
