### ISSUE TITLE
`FileNotFoundException` when mounting NFSRODS

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_nfsrods#186]
To reproduce:
1. Start the `nfsrods` docker container
2. Mount
3. Wait until the docker container's logs stop "scrolling" and you'll be able to see the error message

The full error logs:
```
2023-07-27 12:46:32 2023-07-27 16:46:32.396 DEBUG Thread-34 [IRODSVirtualFileSystem] - list - Listing contents of [/tempZone/trash] ...
2023-07-27 12:46:32 2023-07-27 16:46:32.401 ERROR Thread-34 [IRODSVirtualFileSystem] - unable to find file under path
2023-07-27 12:46:32 2023-07-27 16:46:32.402 ERROR Thread-34 [NFSServerV41] - Unhandled exception:
2023-07-27 12:46:32 java.io.IOException: org.irods.jargon.core.exception.FileNotFoundException: unable to find file under path
2023-07-27 12:46:32     at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.list(IRODSVirtualFileSystem.java:1022) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.nfs.vfs.PseudoFs.list(PseudoFs.java:211) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.nfs.v4.OperationREADDIR.process(OperationREADDIR.java:108) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.nfs.v4.AbstractOperationExecutor.execute(AbstractOperationExecutor.java:58) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:188) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.lambda$run$0(RpcDispatcher.java:100) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
2023-07-27 12:46:32     at javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
2023-07-27 12:46:32     at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:99) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at java.lang.Thread.run(Thread.java:833) [?:?]
2023-07-27 12:46:32 Caused by: org.irods.jargon.core.exception.FileNotFoundException: unable to find file under path
2023-07-27 12:46:32     at org.irods.jargon.core.pub.CollectionListingUtils.handleNoObjStatUnderRootOrHomeByLookingForPublicAndHome(CollectionListingUtils.java:260) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.irods.jargon.core.pub.CollectionListingUtils.retrieveObjectStatForPath(CollectionListingUtils.java:1181) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl.retrieveObjectStatForPath(CollectionAndDataObjectListAndSearchAOImpl.java:1661) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.listDataObjectsAndCollectionsUnderPathWithPermissions(IRODSVirtualFileSystem.java:903) ~[nfsrods.jar:?]
2023-07-27 12:46:32     at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.list(IRODSVirtualFileSystem.java:983) ~[nfsrods.jar:?]
2023-07-27 12:46:32     ... 12 more
```

**Comment by trel** [comment]
Need to investigate/reproduce.

**Comment by korydraughn** [comment]
The exception indicates Jargon could not find `/tempZone/trash`. Perhaps this was caused by a bad configuration, missing trash collection, or invalid arguments to the mount command.

In any case, the application did its job by reporting an error.

I don't think there's anything actionable here.

**Comment by trel** [comment]
That sounds fine.   Closing as resolved/invalid.
