### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException on docker run command

### ISSUE THREAD

**Issue by ac55-sanger** [irods/irods_client_nfsrods#93]
With the latest code, the docker run command is failing with java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException exception.

Steps followed:
```
$ git clone https://github.com/irods/irods_client_nfsrods.git

$ cd irods_client_nfsrods

$ docker build -t nfsrods .

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
nfsrods             latest              e611f2c8a946        About a minute ago   780MB
ubuntu              16.04               330ae480cb85        6 days ago           125MB

$ docker run --rm nfsrods sha
Cert not found for NFSRODS - not importing
Build Time    => 2020-06-23T13:01:26+0000
Build Version => 1.0.0
Build SHA     => 1b8f029c90de31811a9e4e2e75be118ffed498b3

$ docker run --name nfsrods -p 2049:2049 -v /nfsrods_config:/nfsrods_config:ro -v /etc/hosts:/etc/hosts:ro nfsrods:latest
Cert not found for NFSRODS - not importing
2020-06-23 13:06:14.510 INFO  Thread-1 [ServerMain] - Build Time    => 2020-06-23T13:01:26+0000
2020-06-23 13:06:14.518 INFO  Thread-1 [ServerMain] - Build Version => 1.0.0
2020-06-23 13:06:14.518 INFO  Thread-1 [ServerMain] - Build SHA     => 1b8f029c90de31811a9e4e2e75be118ffed498b3
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException
	at com.fasterxml.jackson.databind.deser.std.JdkDeserializers.<clinit>(JdkDeserializers.java:26)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1811)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:161)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:125)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:478)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4273)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4082)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2979)
	at org.irods.nfsrods.utils.JSONUtils.fromJSON(JSONUtils.java:50)
	at org.irods.nfsrods.vfs.ServerMain.main(ServerMain.java:67)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.InputCoercionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more
```

**Comment by trel** [comment]
Hm... will look at this ASAP.   Thanks.

**Comment by trel** [comment]
Reproduced - will get a fix in.

**Comment by michael-conway** [comment]
I'd drop a dependency into the maven pom.xml and see if it's happy. Does @korydraughn need an assist here?

**Comment by korydraughn** [comment]
Like @michael-conway said, this is likely due to the other jackson dependencies not being updated. I'll verify when I get a chance.
https://github.com/irods/irods_client_nfsrods/blob/1b8f029c90de31811a9e4e2e75be118ffed498b3/irods-vfs-impl/pom.xml#L100-L116
