### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#97]
Our users are complaining about generally unreliable experiences using our NFSRODS deployment, so I am auditing our logs for error messages. Among them we have 205,736 instances of the error "ERROR Thread-?? [ReadWriteAclWhitelist] - java.net.ConnectException: Connection refused (Connection refused)".

A sample of 10000 instances indicates that this is the most common traceback:

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_222]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_222]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_222]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_222]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.connect(IRODSBasicTCPConnection.java:142) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.initializeConnection(AbstractConnection.java:232) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractConnection.<init>(AbstractConnection.java:197) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.<init>(IRODSBasicTCPConnection.java:51) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl.instance(IRODSTCPConnectionFactoryImpl.java:33) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:86) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSGenQueryExecutorImpl.<init>(IRODSGenQueryExecutorImpl.java:57) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getIRODSGenQueryExecutor(IRODSAccessObjectFactoryImpl.java:281) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.nfsrods.vfs.ReadWriteAclWhitelist.lambda$new$1(ReadWriteAclWhitelist.java:64) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

But there are other variants.

**Comment by anderbubble** [comment]
These appear to be related to an underlying issue that I can target more specifically, so I'll close this one out.
