### ISSUE TITLE
Unknown iRODS exception code recieved:-514030

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_client_nfsrods#99]
Our users are complaining about generally unreliable experiences using our NFSRODS deployment, so I am auditing our logs for error messages. Among them we have 186,801 instances of the error "[IRODSVirtualFileSystem] - org.irods.jargon.core.exception.JargonException: Unknown iRODS exception code recieved:-514030".

A sample of 10000 instances indicates that this is the most common traceback:

```
org.irods.jargon.core.exception.JargonException: Unknown iRODS exception code recieved:-514030
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:105) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1399) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:903) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:871) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:284) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:410) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.fileClose(IRODSFileSystemAOImpl.java:950) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.io.IRODSFileImpl.close(IRODSFileImpl.java:1320) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.jargon.core.pub.io.IRODSRandomAccessFile.close(IRODSRandomAccessFile.java:1056) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.nfsrods.vfs.IRODSVirtualFileSystem$AutoClosedIRODSRandomAccessFile.close(IRODSVirtualFileSystem.java:1585) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.irods.nfsrods.vfs.IRODSVirtualFileSystem.write(IRODSVirtualFileSystem.java:1210) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.vfs.PseudoFs.write(PseudoFs.java:291) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.OperationWRITE.process(OperationWRITE.java:82) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:204) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.lambda$run$0(RpcDispatcher.java:100) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_222]
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:99) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) ~[nfsrods-0.9.3-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

But there are other variants.

**Comment by anderbubble** [comment]
I think this one is more accurately described using underling issues, so I'll re-open with different information.
